ValueSet and CodeSystem display updates
standardhealth/shr-fhir-export pull request #107
Opened 2018-09-12 16:00 UTC by kjmahalingam

Fixes #104 as described in that issue.

2018-09-12 19:19 UTC, cmoesel requested changes
A good start, but I think some changes are needed.  See individual comments for details.

Please also test both with the `hideSupporting` flag turned on and it turned off, to ensure you get the expected results.

2018-09-12 19:19 UTC, cmoesel commented on lib/ig.js
> +    if (valueSet.url.startsWith(config.projectURL)) {
I don't think you need this `if` statement.  If it's in `fhirResults.valueSets`, then it should be one of our local value sets.

2018-09-12 19:19 UTC, cmoesel commented on lib/ig.js
> +        }
Since I don't _think_ `fhirResults.valueSets` will _ever_ have external value sets, I don't think this check is needed here.  Just throw it right into `primaryLocalValueSetUrls` (like it was before).  In other words, I don't think there should be _any_ diff here.

2018-09-12 19:19 UTC, cmoesel commented on lib/ig.js
> +    if (primaryLocalValueSetUrls.has(valueSet.url)) {
You dropped `!hideSupporting` from the condition.  Was that intentional?  Now if the config has `hideSupporting` as `false` (or missing), they'll _still_ only get primary value sets (and none of the supporting ones).

2018-09-12 19:19 UTC, cmoesel commented on lib/ig.js
> +  for (const url of sortedPrimaryExternalValueSetUrls) {
Similar to above, do you have any mechanism for showing _non-primary_ external value sets if the config doesn't have `hideSupporting` set? It seems like we'll always only get the primary ones?

2018-09-12 19:19 UTC, cmoesel commented on lib/ig.js
> +          }
It's up to you, but you probably could just collect _all_ used value sets in one list and then use this logic to separate them out later.  Then you wouldn't have as much duplicate code in the part where you process extensions.

But that's up to you...  This code is only duplicated once, so it's not a super big deal.

2018-09-12 19:19 UTC, cmoesel commented on lib/ig.js
> +    .replace('<local-value-sets-header/>', '<h2>Local Value Sets used in this Implementation Guide</h2>')
In the current code on master, we change the header text based on if `hideSupporting` was set or not (so it would say "Primary value sets..." if `hideSupporting` was true).  See lines 471-473 in original source code. This gives the reader a clue that some things may be filtered out.  It seems you may have lost that here.

I also would suggest that perhaps it should be "defined in this" instead of "used in this".

2018-09-12 19:19 UTC, cmoesel commented on lib/ig.js
> +    .replace('<external-value-sets-header/>', '<h2>External Value Sets used in this Implementation Guide</h2>')
As noted before, we probably also should be distinguishing whether it's _primary_ external value sets or not.

2018-09-12 19:19 UTC, cmoesel commented on lib/ig.js
> +  let updatedCodeSystemsHtml = codeSystemsHtml.replace('<code-systems-go-here/>', htmlCodeSystems.join(''))
Same comment as w/ value sets -- you dropped the functionality that used to indicate if only _primary_ code systems were shown (see lines 490-492 in original source).

2018-09-12 20:01 UTC, kjmahalingam commented
I'll work to address the changes over the week, and then will discuss with @rutemartins to ensure that everything is still as expected.

2018-09-13 14:29 UTC, kjmahalingam commented
The comments above have all been addressed and this should be functional. I've tested with hiding and not hiding supporting resources and it worked as expected.

As far as clean code is concerned, this does have similar code in multiple locations when iterating through a profile/extension to collect value sets as necessary (primary profile, supporting profile, primary extension, and supporting extension). It's not identical, since different sets are added to in each of these locations, and the logic is slightly different. If there are suggestions about how this could be abstracted, I can work to do that. Otherwise, if we think these are different and distinct enough, I think this should be ready.

2018-09-20 01:03 UTC, cmoesel commented
The code looks great and the results looks great!  I think there is still an open question, however, regarding whether or not the external value sets should be linked or just plain text.  I've asked the question over on #104.

2018-09-20 01:06 UTC, cmoesel commented
BTW -- I *think* we have a way to get the human-readable names for all of the core FHIR and US Core value sets.  The shr-fhir-exporter has all of the FHIR and US Core value set definition files available to it -- so we could look up the definitions by URL and then pull the value set titles from the definition files.  It wouldn't work for non-FHIR/non-US-Core value sets (like the LOINC ones), but it's probably better some than none!

I'm fine with that being a separate task, but I think it *is* worth doing.

2018-09-20 23:35 UTC, rutemartins commented
Agree with @cmoesel. The more value set names we can resolve, the better. I imagine there will always be a relatively limited number of sources we will be referencing value sets from, so if we tackle FHIR value sets now, we can think about LOINC and VSAC later (and those have other issues beyond our control).

2018-09-21 11:32 UTC, kjmahalingam commented
I will work to add in this functionality in the near future.

2018-09-24 19:51 UTC, kjmahalingam commented
The described functionality for fixing the broken US Core links and adding in names for external VS wherever possible has been implemented. @cmoesel, if this looks good, should be ready to merge.

2018-09-25 18:53 UTC, cmoesel approved these changes

2018-09-25 18:56 UTC, cmoesel commented
This looks great.

Have you ever read the story, "If You Give a Mouse a Cookie"?  If you have, then you're prepared for the next paragraph.

It seems a shame to have a nice two-column table at the top and a one-column table at the bottom with no descriptions.  But... as it turns out, those value set files where you found the name?  They also have an optional "description" field.  So... you *could* build a two-column table and include descriptions of the known external value sets.

That's a bonus task.  If you have time to tackle it, then _do it_.  But if you don't, then let's merge this, call it done, and pick up the descriptions as a separate task.

2018-09-25 19:12 UTC, kjmahalingam commented
I think that extra task can get finished by tomorrow morning, so I will work to get that done!

2018-09-26 12:16 UTC, kjmahalingam commented
@cmoesel, the mouse now has a glass of milk. Let me know if he needs a straw too. (It's done, let me know if there's anything else to fix up).

2018-09-26 17:37 UTC, cmoesel commented on lib/ig.js
> +  console.log(externalValueSetInfo);
Oops.  Kill the console log!

2018-09-26 17:42 UTC, cmoesel commented
Awesome.  Only issue I noticed was a stray `console.log` statement that needs to be deleted.  After that, I'm ready to merge!

2018-09-26 18:09 UTC, kjmahalingam commented
It's gone!

2018-09-26 18:13 UTC, merged