Decentralize loggerific errorMessages.txt
standardhealth/shr-fhir-export pull request #156
Opened 2019-08-27 12:24 UTC by ngfreiter

This takes the `errorMessages.txt` file which existed only in `shr-cli` and splits it into multiple files, so that each module has its own `errorMessages.txt` file. Also incorrectly numbered or otherwise broken errors were fixed.

PR 4/7
Affects:
- `shr-cli`
- `shr-text-import`
- `shr-expand`
- `shr-fhir-export`
- `shr-json-schema-export`
- `shr-json-javadoc`
- `shr-es6-export`

2019-08-28 14:16 UTC, cmoesel requested changes
Very minor feedback...

2019-08-28 14:16 UTC, cmoesel commented on lib/export.js
> +  return require('path').join(__dirname, '../errorMessages.txt');
You can probably guess what I'm going to say, right?
```javascript
  return require('path').join(__dirname, '..', 'errorMessages.txt');
```

2019-08-28 14:16 UTC, cmoesel commented on lib/extensions.js
> +          logger.error({ elementId: value.effectiveIdentifier.name }, '13115');
Probably should be `.fqn` rather than `.name`.

2019-08-28 15:12 UTC, ngfreiter commented on lib/export.js
> +  return require('path').join(__dirname, '../errorMessages.txt');
Fixed this here https://github.com/standardhealth/shr-fhir-export/pull/156/commits/bb4474b7d14b86a69751a11ac5823172460b5abf.

2019-08-28 15:12 UTC, ngfreiter commented on lib/extensions.js
> +          logger.error({ elementId: value.effectiveIdentifier.name }, '13115');
Fixed this here https://github.com/standardhealth/shr-fhir-export/pull/156/commits/bb4474b7d14b86a69751a11ac5823172460b5abf.

2019-08-28 17:30 UTC, cmoesel commented
Changes all look good.  Holding off on merging pending a decision on whether we want this in master yet.  See: https://github.com/standardhealth/shr-cli/pull/227#pullrequestreview-280987415

2019-09-11 18:49 UTC, cmoesel approved these changes
Looks good.  I may squash or rebase this to clean up commits before merging.

2019-09-11 21:19 UTC, merged