No diff profiles
standardhealth/shr-fhir-export pull request #64
Opened 2017-12-05 19:08 UTC by cmoesel

The primary purpose of this pull request is to _not_ create profiles for SHR elements that map cleanly to FHIR (e.g., there are no additional constraints or changes to the original FHIR type).  The SHR element `Coding` is a good example.  Since it doesn't constrain anything in FHIR `Coding`, an SHR profile for `Coding` is _not_ produced -- and all other elements that refer to `Coding` will use the FHIR `Coding` instead of a specific SHR `Coding`.

This implementation introduces more possibility for recursive profile definition -- so new logging capabilities have also been added to detect this situation when it might adversely affect the results.

This also introduces a few bug fixes, most notably being a bug that caused many elements in the profiles to be "unrolled" (i.e. expanded) when that was not at all necessary.

2017-12-05 20:49 UTC, cmoesel commented
Just pushed a bonus feature: the profiles, extensions, etc are now properly sorted in the IG.

2017-12-06 16:39 UTC, Abhijay reviewed
Looked carefully over code, found no egregious errors or obvious logical errors. Walked through code on debugger and saw expected results at the intermediate steps. Output reduces total number of errors. Looks good to me!

2017-12-06 16:41 UTC, Abhijay requested changes
Only needs package version number bumped before merging in.

2017-12-06 16:48 UTC, Abhijay approved these changes

2017-12-06 16:48 UTC, merged